### ISSUE TITLE
The plugin doesn't work on windows 10

### ISSUE THREAD

**Issue by fdesforges** [ryanrosello-og/playwright-vscode-trace-viewer#1]
The generated command is : 

`npx playwright show-trace d:\folder\trace.zip`

the errors message is  :
`No such file or directory d:foldertrace.zip`

A working command can be on windows 10 : 
`npx playwright show-trace "d:\folder\trace.zip"`

Good initiative for such plugin, really helpfull for debugging trace (without passing by command line)

**Comment by ryanrosello-og** [comment]
@fdesforges this has been fixed in https://github.com/ryanrosello-og/playwright-vscode-trace-viewer/pull/4
Try upgrading the extension to v1.0.2
